### ISSUE TITLE
Naming convention

### ISSUE THREAD

**Issue by tiagostutz** [flaviostutz/schelly#1]
Reading the documentation I was wondering: how about calling the "Backup Utility" as "Backup Repository"? I think the **Repository** word is directly related to "CREATE", "READ" and DELETE, which are effectively what the webhook specifies.

What do you think?

**Comment by flaviostutz** [comment]
It is not just the repository, because it will do the job of gathering and preparing the data that will be backup in a repository. Maybe Backuper?

**Comment by tiagostutz** [comment]
I understand the meaning of  "Backuper", but in IMHO this name is more like a product name than the name of a component, that's because I'd not use it.

I don't know, although it indeed gathers and prepares the data, from a Schelly perspective, this component still behaves like a repo to me.

Take a look at https://en.wikipedia.org/wiki/Backup and search for "repository"
